name: 'Run Upptime Monitor'
description: 'Runs upptime/uptime-monitor with custom retry logic patches'
inputs:
  command:
    description: 'Command to run (update, graphs, response-time, site, readme, etc.)'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
  secrets-context:
    description: 'Secrets context (JSON)'
    required: false
    default: '{}'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache uptime-monitor build
      id: cache-uptime-monitor
      uses: actions/cache@v4
      with:
        path: /tmp/uptime-monitor-build
        key: uptime-monitor-v1.41.0-custom-${{ hashFiles('.github/retry-fix.patch') }}

    - name: Checkout uptime-monitor
      if: steps.cache-uptime-monitor.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: upptime/uptime-monitor
        ref: v1.41.0
        path: /tmp/uptime-monitor-source

    - name: Apply patch and build
      if: steps.cache-uptime-monitor.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd /tmp/uptime-monitor-source
        git apply "$GITHUB_WORKSPACE/.github/retry-fix.patch"
        npm ci
        npm run build
        mkdir -p /tmp/uptime-monitor-build
        cp -r dist node_modules package.json /tmp/uptime-monitor-build/

    - name: Run uptime-monitor command
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        INPUT_COMMAND: ${{ inputs.command }}
        GH_PAT: ${{ inputs.github-token }}
        SECRETS_CONTEXT: ${{ inputs.secrets-context }}
      run: |
        node /tmp/uptime-monitor-build/dist/index.js
